#!/bin/sh

log() {
  echo "$1" | systemd-cat
}

launch_strict() {
  CONFIG_FILE="$SNAP/etc/config.yaml"
  CONFIG_FOLDER="/etc/otelcol/config.d"

  # If the snap can access $CONFIG_FOLDER and there is at least one file inside
  if snapctl is-connected etc-otelcol-config && [ -r "$CONFIG_FOLDER/*" ]; then
    log "Launching with config files from $CONFIG_FOLDER"
    CONFIG_ARG=""
    for file in $CONFIG_FOLDER/*; then
      CONFIG_ARG="${CONFIG_ARG} --config ${file}"
    end
  else
    log "Launching with minimal default config from the snap"
    CONFIG_ARG="--config ${CONFIG_FILE}"
  fi

  exec "$SNAP/bin/otelcol" "$CONFIG_ARG"
}

launch_strict
