title: OpenTelemetry Collector Snap
name: opentelemetry-collector
version: '0.152.0'
summary: Vendor-agnostic way to receive, process and export telemetry data.
license: Apache-2.0
description: |
  Designed to collect, process, and export telemetry data such as metrics, logs,
  and traces from various sources to multiple destinations.
contact: jose.masson@canonical.com
issues: https://github.com/canonical/opentelemetry-collector-snap/issues
source-code: https://github.com/canonical/opentelemetry-collector-snap
website: https://opentelemetry.io/docs/collector/
base: core24
platforms:
  amd64:
  arm64:
  ppc64el:
  s390x:
confinement: strict

plugs:
  etc-otelcol-config:
    interface: system-files
    read:
      - /etc/otelcol/config.d
  logs:
    interface: content
    target: $SNAP/shared-logs
  proc-sys-kernel-random:
    interface: system-files
    read:
      - /proc/sys/kernel/random/write_wakeup_threshold
      - /proc/sys/kernel/random/read_wakeup_threshold
      - /proc/sys/kernel/random/poolsize
      - /proc/sys/kernel/random/urandom_min_reseed_secs
      - /proc/spl/kstat/zfs
      - /sys/fs/btrfs
      - /proc/sys/kernel/threads-max

apps:
  opentelemetry-collector:
    daemon: simple
    command: command-wrapper
    install-mode: disable
    restart-condition: on-failure
    plugs:
      - network-bind
      - time-control
      - hardware-observe
      - mount-observe
      - network-observe
      - system-observe
      - log-observe           # Required to parse and fetch host journals via journalctl
      - etc-otelcol-config
      - proc-sys-kernel-random
      - home

parts:
  wrapper:
    plugin: dump
    source: ./snap
    source-type: local
    override-build: |
      cp local/command-wrapper $CRAFT_PART_INSTALL/

  ocb:
    plugin: go
    source: "https://github.com/open-telemetry/opentelemetry-collector.git"
    source-type: "git"
    source-tag: "v0.152.0"
    source-depth: 1
    source-subdir: "cmd/builder"
    build-snaps:
      - go/1.25/candidate
    build-environment:
      - CGO_ENABLED: "1"     # Required for building journald C extensions
      - GOOS: linux
    stage:
      - bin/builder
    prime:
      - "-*"

  opentelemetry-collector:
    after:
      - ocb
    plugin: dump
    source: .
    build-packages:
      - wget
      - libsystemd-dev
      - build-essential
      - pkg-config
    override-build: |
      mkdir -p ${CRAFT_PART_BUILD}/snap
      wget https://raw.githubusercontent.com/canonical/opentelemetry-collector-rock/refs/heads/main/0.152.0/config.yaml -O ${CRAFT_PART_BUILD}/snap/config.yaml
      wget https://raw.githubusercontent.com/canonical/opentelemetry-collector-rock/refs/heads/main/0.152.0/manifest.yaml -O ${CRAFT_PART_BUILD}/snap/manifest.yaml
      
      sed -i '/receivers:[[:space:]]*/a \  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/journaldreceiver v0.152.0' ${CRAFT_PART_BUILD}/snap/manifest.yaml
      
      builder --config="${CRAFT_PART_BUILD}/snap/manifest.yaml"
      install -D -m755 ${CRAFT_PART_BUILD}/_build/otelcol ${CRAFT_PART_INSTALL}/bin/otelcol
      install -D ${CRAFT_PART_BUILD}/snap/config.yaml ${CRAFT_PART_INSTALL}/etc/config.yaml