name: otel-collector 
base: core24 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: OTEL Collector for SnapD
description: |
  This is the standard OTEL collector as a snap for integration with SnapD

grade: devel # must be 'stable' to release into candidate/stable channels
platforms:
  amd64:
  arm64:
confinement: strict # use 'strict' once you have the right plugs and slots


parts:
  otelcorecol:
    # See 'snapcraft plugins'
    plugin: go 
    build-snaps: [go/latest/stable]
    source: .
    override-build: |
      make install-tools
      make otelcorecol
    override-stage: |
      craftctl default 
      cp -r ${SNAPCRAFT_PART_BUILD}/bin/. ${SNAPCRAFT_PRIME}/bin/
      
apps:
  collector:
    command: bin/otelcorecol_linux_amd64
    daemon: simple
    plugs:
      - network