name: Build

on:
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          sudo snap install snapcraft --classic --stable
          sudo snap install lxd
          sudo lxd waitready
          sudo lxd init --minimal
          sudo lxc network set lxdbr0 ipv6.address none
          sudo chmod a+wr /var/snap/lxd/common/lxd/unix.socket
          sudo usermod -a -G lxd "$USER"
          sudo iptables -F FORWARD
          sudo iptables -P FORWARD ACCEPT
      - name: Run tests
        run: snapcraft test
